# 数据库四要素
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username : root
    password : 123456
# 文件大小，单个文件最大10，单次最大100
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size : 100MB


mybatis:
  configuration:
#     开启mybatis驼峰映射 a_clomn --> aClomn
    map-underscore-to-camel-case : true
#    日志 输出到控制台
    log-impl : org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云oss配置
aliyun:
  oss:
    endpoint: # 填自己的
    accessKeyId: # 填自己的
    accessKeySecret: # 填自己的
    bucketName: # 填自己的
#   spring??????

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
